#!/usr/bin/env bash

#------------------------------------
# Config and theme
#------------------------------------

file="$HOME/.config/rofi/themes/powermenu.rasi"

username=" $(whoami)"

#------------------------------------
# Run rofi
#------------------------------------

rofi_cmd() {
    rofi -dmenu \
        -p "$username" \
        -mesg "Power Menu" \
        -theme ${file}
}

#------------------------------------
# Run rofi menu
#------------------------------------

#Options
shutdown=''
reboot=''
lock=''
suspend=''
logout=''

run_rofi() {
    echo -e "$lock\n$suspend\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

#------------------------------------
# Run cmds
#------------------------------------

chosen="$(run_rofi)"
case ${chosen} in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        if [[ -x '/usr/bin/betterlockscreen' ]]; then
            betterlockscreen -l
        elif [[ -x '/usr/bin/i3lock' ]]; then
            i3lock
        fi
        ;;
    $suspend)
        mpc -q pause
        amixer set Master mute
        systemctl suspend
        ;;
    $logout)
        pkill -KILL -u "$USER"
        ;;
esac
